### ISSUE TITLE
cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by rich1488** [vladh/irabot#1]
```
/home/pi/discordbots/irabot/index.js:120
  if (title_match.length < 2) {
                  ^

TypeError: Cannot read properties of null (reading 'length')
    at get_media_info_from_html (/home/pi/discordbots/irabot/index.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.play (/home/pi/discordbots/irabot/index.js:160:16)
    at async Client.<anonymous> (/home/pi/discordbots/irabot/index.js:249:7)

```
what does this mean?

**Comment by vladh** [comment]
Hi! First of all, apologies for the quick and dirty code, I never expected anyone else to use this bot. I've pushed a change that fixes this crash.

Secondly, the error means the bot could not get the metadata of the podcast you're trying to get. Right now, irabot only supports Overcast URLs. This shouldn't be a problem, since most podcasts will be on Overcast. Simply find the Overcast page for the episode you're trying to listen to, and use that.

Hope that helped! Feel free to ask if you have any other questions.
